#!/usr/bin/env bash
# Copy the conformance spec of smallchat (TypeScript, @smallchat/core) into
# this package, so the Swift runtime is tested against the same golden
# vectors and fixtures as the TypeScript one.
#
#   Scripts/sync-spec.sh <path to a smallchat checkout>
#
# - <checkout>/spec/** is copied to Tests/Fixtures/spec/ (replacing it).
# - Tests/Fixtures/spec/SOURCE records where it came from: the checkout's
#   commit and any uncommitted changes under spec/ at the time of the copy.
# - Sources/SmallChatCore/Artifact/ArtifactSchema.swift is regenerated from
#   spec/artifact/artifact.v1.schema.json (the loader validates against it).
#
# Run `swift test --filter SmallChatConformanceTests` afterwards.
set -euo pipefail

src="${1:?usage: Scripts/sync-spec.sh <path to a smallchat (TypeScript) checkout>}"
root="$(cd "$(dirname "$0")/.." && pwd)"
dest="$root/Tests/Fixtures/spec"
schema_swift="$root/Sources/SmallChatCore/Artifact/ArtifactSchema.swift"

if [ ! -d "$src/spec" ]; then
  echo "error: $src/spec does not exist (expected a smallchat checkout)" >&2
  exit 1
fi
if [ ! -f "$src/spec/artifact/artifact.v1.schema.json" ]; then
  echo "error: $src/spec/artifact/artifact.v1.schema.json is missing" >&2
  exit 1
fi

rm -rf "$dest"
mkdir -p "$dest"
cp -R "$src/spec/." "$dest/"

commit="unknown (not a git checkout)"
dirty=""
if git -C "$src" rev-parse --git-dir >/dev/null 2>&1; then
  commit="$(git -C "$src" rev-parse HEAD)"
  dirty="$(git -C "$src" status --porcelain --untracked-files=all -- spec || true)"
fi

{
  echo "Copied from smallchat (TypeScript) spec/ by Scripts/sync-spec.sh."
  echo "commit: $commit"
  echo "copied: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [ -n "$dirty" ]; then
    echo "uncommitted changes under spec/ at copy time (git status --porcelain):"
    echo "$dirty" | sed 's/^/  /'
  else
    echo "uncommitted changes under spec/ at copy time: none"
  fi
} > "$dest/SOURCE"

schema_text="$(cat "$src/spec/artifact/artifact.v1.schema.json")"
case "$schema_text" in
  *'"""#'*) echo "error: the schema contains \"\"\"#, which cannot go in a raw string literal" >&2; exit 1 ;;
esac
{
  echo "// Generated by Scripts/sync-spec.sh from smallchat spec/artifact/artifact.v1.schema.json."
  echo "// Do not edit: re-run the script to update it."
  echo ""
  echo "/// The normative JSON Schema (draft 2020-12) of artifact format 1.0."
  echo "public let artifactV1SchemaJSON = #\"\"\""
  printf '%s\n' "$schema_text"
  echo "\"\"\"#"
} > "$schema_swift"

echo "Copied $src/spec to $dest"
echo "Regenerated $schema_swift"
cat "$dest/SOURCE"
