import Foundation
#if canImport(CryptoKit)
import CryptoKit
#endif

// MARK: - Paths

private let artifactsDir = ".smallchat/artifacts"
private let manifestFile = "manifest.json"

private func artifactsDirPath(_ projectDir: String) -> String {
    (projectDir as NSString).appendingPathComponent(artifactsDir)
}

private func manifestPath(_ projectDir: String) -> String {
    (artifactsDirPath(projectDir) as NSString).appendingPathComponent(manifestFile)
}

private func ensureArtifactsDir(_ projectDir: String) throws {
    try FileManager.default.createDirectory(
        atPath: artifactsDirPath(projectDir),
        withIntermediateDirectories: true
    )
}

// MARK: - Manifest Management

/// Load the artifact version manifest, or return a fresh empty manifest.
public func loadArtifactManifest(_ projectDir: String) -> ArtifactManifest {
    let path = manifestPath(projectDir)
    guard FileManager.default.fileExists(atPath: path),
          let data = FileManager.default.contents(atPath: path),
          let manifest = try? JSONDecoder().decode(ArtifactManifest.self, from: data) else {
        return ArtifactManifest()
    }
    return manifest
}

/// Save the artifact version manifest to disk.
public func saveArtifactManifest(_ projectDir: String, _ manifest: ArtifactManifest) throws {
    try ensureArtifactsDir(projectDir)
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    let data = try encoder.encode(manifest)
    try data.write(to: URL(fileURLWithPath: manifestPath(projectDir)))
}

// MARK: - Versioning Operations

/// Archive the current active artifact into the versioned store.
/// Returns the created ArtifactVersion, or nil if no artifact exists.
public func archiveCurrentArtifact(
    _ projectDir: String,
    outputPath: String,
    isAutoGenerated: Bool
) -> ArtifactVersion? {
    let sourcePath = (projectDir as NSString).appendingPathComponent(outputPath)
    let fm = FileManager.default

    guard fm.fileExists(atPath: sourcePath),
          let content = fm.contents(atPath: sourcePath) else {
        return nil
    }

    do {
        try ensureArtifactsDir(projectDir)
    } catch {
        return nil
    }

    let hash = sha256Hex(content)
    let timestamp = ISO8601DateFormatter().string(from: Date()).replacingOccurrences(of: ":", with: "-").replacingOccurrences(of: ".", with: "-")
    let baseName = (outputPath as NSString).deletingPathExtension
    let suffix = isAutoGenerated ? ".auto" : ""
    let versionedName = "\(baseName).\(timestamp)\(suffix).json"
    let versionedPath = (artifactsDirPath(projectDir) as NSString).appendingPathComponent(versionedName)

    do {
        try fm.copyItem(atPath: sourcePath, toPath: versionedPath)
    } catch {
        return nil
    }

    // Extract tool count from artifact
    var toolCount = 0
    if let json = try? JSONSerialization.jsonObject(with: content) as? [String: Any],
       let stats = json["stats"] as? [String: Any],
       let count = stats["toolCount"] as? Int {
        toolCount = count
    }

    let version = ArtifactVersion(
        path: versionedPath,
        timestamp: ISO8601DateFormatter().string(from: Date()),
        isAutoGenerated: isAutoGenerated,
        toolCount: toolCount,
        hash: hash
    )

    // Update manifest
    var manifest = loadArtifactManifest(projectDir)
    manifest.versions.insert(version, at: 0) // newest first

    if !isAutoGenerated {
        manifest.lastManualVersion = versionedPath
    }

    try? saveArtifactManifest(projectDir, manifest)

    return version
}

/// Promote a new artifact to be the active version.
public func promoteArtifact(
    _ projectDir: String,
    newArtifactPath: String,
    outputPath: String
) {
    let destPath = (projectDir as NSString).appendingPathComponent(outputPath)
    let fm = FileManager.default

    try? fm.removeItem(atPath: destPath)
    try? fm.copyItem(atPath: newArtifactPath, toPath: destPath)

    var manifest = loadArtifactManifest(projectDir)
    manifest.currentVersion = destPath
    try? saveArtifactManifest(projectDir, manifest)
}

/// Rollback to the last non-auto-generated (manual) artifact version.
/// Returns the restored version, or nil if no fallback exists.
public func rollbackToFallback(
    _ projectDir: String,
    outputPath: String
) -> ArtifactVersion? {
    let manifest = loadArtifactManifest(projectDir)
    let fm = FileManager.default

    // Find the last manual version
    if let manualVersion = manifest.versions.first(where: { !$0.isAutoGenerated }),
       fm.fileExists(atPath: manualVersion.path) {
        let destPath = (projectDir as NSString).appendingPathComponent(outputPath)
        try? fm.removeItem(atPath: destPath)
        try? fm.copyItem(atPath: manualVersion.path, toPath: destPath)

        var updated = manifest
        updated.currentVersion = destPath
        try? saveArtifactManifest(projectDir, updated)
        return manualVersion
    }

    // Try lastManualVersion path
    if let lastManual = manifest.lastManualVersion, fm.fileExists(atPath: lastManual) {
        let destPath = (projectDir as NSString).appendingPathComponent(outputPath)
        try? fm.removeItem(atPath: destPath)
        try? fm.copyItem(atPath: lastManual, toPath: destPath)

        var updated = manifest
        updated.currentVersion = destPath
        try? saveArtifactManifest(projectDir, updated)

        if let data = fm.contents(atPath: lastManual) {
            return ArtifactVersion(
                path: lastManual,
                timestamp: ISO8601DateFormatter().string(from: Date()),
                isAutoGenerated: false,
                toolCount: 0,
                hash: sha256Hex(data)
            )
        }
    }

    return nil
}

/// Prune old artifact versions, respecting retention rules.
/// Returns paths that were deleted.
public func pruneOldVersions(
    _ projectDir: String,
    maxRetained: Int
) -> [String] {
    var manifest = loadArtifactManifest(projectDir)
    var deleted: [String] = []
    let fm = FileManager.default

    guard manifest.versions.count > maxRetained else { return deleted }

    let manualVersions = manifest.versions.filter { !$0.isAutoGenerated }
    let autoVersions = manifest.versions.filter { $0.isAutoGenerated }

    let excess = manifest.versions.count - maxRetained

    // Prune auto-generated versions first (oldest = end of array since newest first)
    let autoPruneCount = min(excess, autoVersions.count)
    let autoToPrune = autoVersions.suffix(autoPruneCount)

    for version in autoToPrune {
        try? fm.removeItem(atPath: version.path)
        deleted.append(version.path)
    }

    // If still need to prune, remove old manual versions (keep at least 1)
    let remaining = excess - autoPruneCount
    if remaining > 0 && manualVersions.count > 1 {
        let manualPruneCount = min(remaining, manualVersions.count - 1)
        let manualToPrune = manualVersions.suffix(manualPruneCount)

        for version in manualToPrune {
            if version.path == manifest.lastManualVersion { continue }
            try? fm.removeItem(atPath: version.path)
            deleted.append(version.path)
        }
    }

    // Update manifest
    let deletedSet = Set(deleted)
    manifest.versions.removeAll { deletedSet.contains($0.path) }
    try? saveArtifactManifest(projectDir, manifest)

    return deleted
}

/// List all artifact versions from the manifest.
public func listArtifactVersions(_ projectDir: String) -> [ArtifactVersion] {
    loadArtifactManifest(projectDir).versions
}

// MARK: - Helpers

private func sha256Hex(_ data: Data) -> String {
    #if canImport(CryptoKit)
    let digest = SHA256.hash(data: data)
    return digest.map { String(format: "%02x", $0) }.joined()
    #else
    // Fallback: simple hash for platforms without CryptoKit
    var hash: UInt64 = 5381
    for byte in data {
        hash = ((hash &<< 5) &+ hash) &+ UInt64(byte)
    }
    return String(format: "%016x", hash)
    #endif
}
